name: 'Code'
 
on:
  push:
    paths:
      - 'src/**'
      - 'build/**'
      - '.github/workflows/code.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'build/**'
      - '.github/workflows/code.yml'
  workflow_dispatch:
 
env:
  NODE_VERSION: '12.x'       

jobs:
  
  # ***********************************************************************
  # JOB : Build and Test
  # ***********************************************************************
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    continue-on-error: false
 
    defaults:
      run:
        shell: pwsh
        working-directory: build
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}      

    - name: Build
      run: ./build.ps1
      continue-on-error: false

    - name: Test
      run: ./test.ps1
      continue-on-error: false      