name: 'Code'
 
on:
  push:
    paths:
      - 'src/**'
      - 'build/**'
      - '.github/workflows/code.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'build/**'
      - '.github/workflows/code.yml'
  workflow_dispatch:
 
env:
  NODE_VERSION: '12.x'       

jobs:
  
  # ***********************************************************************
  # JOB : Build
  # ***********************************************************************
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: Test
 
    defaults:
      run:
        shell: pwsh
        working-directory: build
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}      

    - name: Build Code
      shell: pwsh
      run: ./buildCode.ps1